[package]
name = "unsplash-wezterm"
version = "0.1.0"
edition = "2021"

[lib]
name = "unsplash_wezterm"
crate-type = ["cdylib"]

[dependencies]
libc = "0.2"
reqwest = { version = "0.11", features = ["json", "blocking"] }
serde = { version = "1.0.196", features = ["serde_derive"] }
